services:
  backend:
    env_file:
      - stack.env

  worker:
    env_file:
      - stack.env

  beat:
    env_file:
      - stack.env

  flower:
    environment:
      FLOWER_URL_PREFIX: admin/flower
    env_file:
      - stack.env

  db:
    env_file:
      - stack.env

  redis: {}

  frontend:
    image: ghcr.io/vatger/atciss/atciss-frontend
    ports:
      - "8011:80"
    depends_on:
      - backend
